### ISSUE TITLE
Velocity Estimation

### ISSUE THREAD

**Issue by enginBozkurt** [hehern/lidar_perception#2]
First of all, it is really great project as a lidar perception system. Congrats. 
I am trying apply your project into the  vehicle speed detection using Lİdar Sensor.
Speeds are low than expected  and especially many high speeds' predictions are accumulated near 23m/s.
So, what do you think if we want to tune the speed estimation, which parameteres should we change for this purpose?
Also , you are not using HD maps ,right?

Thanks for your feedback in advance.

**Comment by hehern** [comment]
1.You can modify the measurement_noise and xy_propagation_noise parameters in the lidar_perception.yaml file。
2.No, i don't use the HD maps.

**Comment by enginBozkurt** [comment]
So much appreciated for your feedback.You saved my day. Thanks a lot.

**Comment by SHUNSU321** [comment]
> First of all, it is really great project as a lidar perception system. Congrats.
> I am trying apply your project into the vehicle speed detection using Lİdar Sensor.
> Speeds are low than expected and especially many high speeds' predictions are accumulated near 23m/s.
> So, what do you think if we want to tune the speed estimation, which parameteres should we change for this purpose?
> Also , you are not using HD maps ,right?
> 
> Thanks for your feedback in advance.

hallo enginBozkurt

sorry to interrupt. 

I am trying to use this lidar_perception project to extract the speed and distance of detected cars from my own lidar point cloud data. But I found no clue how to use this program, I launched the lidar_perception.launch, but nothing happened. and where should I put my data? or just run it with rosbag play ?

**Comment by enginBozkurt** [comment]
> > First of all, it is really great project as a lidar perception system. Congrats.
> > I am trying apply your project into the vehicle speed detection using Lİdar Sensor.
> > Speeds are low than expected and especially many high speeds' predictions are accumulated near 23m/s.
> > So, what do you think if we want to tune the speed estimation, which parameteres should we change for this purpose?
> > Also , you are not using HD maps ,right?
> > Thanks for your feedback in advance.
> 
> hallo enginBozkurt
> 
> sorry to interrupt.
> 
> I am trying to use this lidar_perception project to extract the speed and distance of detected cars from my own lidar point cloud data. But I found no clue how to use this program, I launched the lidar_perception.launch, but nothing happened. and where should I put my data? or just run it with rosbag play ?

You should play your Bag file  with ROS . $ rosbag play --clock  <yourbagfile.bag>

**Comment by SHUNSU321** [comment]
> > > First of all, it is really great project as a lidar perception system. Congrats.
> > > I am trying apply your project into the vehicle speed detection using Lİdar Sensor.
> > > Speeds are low than expected and especially many high speeds' predictions are accumulated near 23m/s.
> > > So, what do you think if we want to tune the speed estimation, which parameteres should we change for this purpose?
> > > Also , you are not using HD maps ,right?
> > > Thanks for your feedback in advance.
> > 
> > 
> > hallo enginBozkurt
> > sorry to interrupt.
> > I am trying to use this lidar_perception project to extract the speed and distance of detected cars from my own lidar point cloud data. But I found no clue how to use this program, I launched the lidar_perception.launch, but nothing happened. and where should I put my data? or just run it with rosbag play ?
> 
> You should play your Bag file with ROS . $ rosbag play --clock <yourbagfile.bag>

@enginBozkurt  
Thank you so much for the reply!
I actually played with the rosbag and the rviz worked well, I also run the launch without any problem. 
But I did not see any functions worked as the "results" shown in this project description, such as detection and tracking with box ,show the speed etc. I have no idea where I did wrong. 

what I got right now is like: 

![image](https://user-images.githubusercontent.com/34493255/109129715-3c244b80-7751-11eb-81dd-5e56e28a3041.png)
![image](https://user-images.githubusercontent.com/34493255/109129785-4f371b80-7751-11eb-8d8e-de267618a5be.png)
![image](https://user-images.githubusercontent.com/34493255/109131722-57905600-7753-11eb-9477-692c9a714fb5.png)
![image](https://user-images.githubusercontent.com/34493255/109131151-d5a02d00-7752-11eb-8244-c30c17e6d87c.png)

In rviz, I add all the elements that from lidar_perception topic, but haven't see any box or tracking activities.
My data do not contain pedestrian, is there any problem for my data to use this project?
Since I would like to track the vehicles, do I need to modify the parameters if I want all the functions work?   
or should I do some pre processing for the data? 

Looking forward to your reply!

best regards!

**Comment by PleasantPhoenix** [comment]
@SHUNSU321 @hehern Hello, have you resolved this issue? Can you tell me how to solve it?
